apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../_middlewares
  - _repositories
  - namespace.yaml
  - bugsink
  - gitea
  - locust
  - tools
  - touca
  - sonarqube

namespace: mgd-devbench