apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: flux # Assumes standard Flux labels
  namespaceSelector:
    matchNames:
      - flux-system
  podMetricsEndpoints:
    - port: http-prom 
      path: /metrics
      interval: 10s