apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: main
  namespace: mgd-monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 69.4.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 10m
  releaseName: main
  values:
    grafana:
      defaultDashboardsEnabled: false
      env:
        GF_SERVER_SERVE_FROM_SUB_PATH: true
        
      grafana.ini:
        server:
          domain: "grafana.trusted.nirmalhk7.com"
          root_url: "https://grafana.trusted.nirmalhk7.com"
        auth.generic_oauth:
          enabled: true
          name: Authelia
          icon: signin
          allow_sign_up: true
          scopes: openid profile email groups
          empty_scopes: false
          auth_url: https://secure.trusted.nirmalhk7.com/api/oidc/authorization
          token_url: https://secure.trusted.nirmalhk7.com/api/oidc/token
          api_url: https://secure.trusted.nirmalhk7.com/api/oidc/userinfo
          login_attribute_path: preferred_username
          groups_attribute_path: groups
          name_attribute_path: name
          role_attribute_path: contains(groups, 'grafana_admin') && 'Admin' || 'Viewer'
          use_pkce: true
      sidecar:
        dashboards:
          enabled: true
          label: milano_grafana_dashboard
          labelValue: true
          searchNamespace: ALL

    prometheus:
      prometheusSpec:
        externalUrl: "https://prometheus.trusted.nirmalhk7.com"
        routePrefix: /
        scrapeConfigSelector:
          matchLabels:
            prometheus: prometheus_scraper

    commonLabels:
      milano.level: managed