apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: tailscale-metrics
  labels:
    prometheus: prometheus_scraper
spec:
  staticConfigs:
    - labels:
        job: main-tailscale
      targets:
        - 100.87.0.43:5252
  metricsPath: /metrics