---
- hosts: nginx
  name: Install nginx on 172.16.0.101 via jump host 10.0.0.10
  gather_facts: false
  tasks:
    # - name: Print the SSH password (for debugging, not recommended in production)
    #   debug:
    #     msg: "Password for actual-server is {{ ansible_password }}"
    - name: Install nginx
      become: true
      apt:
        name: nginx
        state: present
        update_cache: yes