apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authelia
  annotations:
    gethomepage.dev/href: "https://secure.trusted.nirmalhk7.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Security
    gethomepage.dev/icon: authelia
    gethomepage.dev/app: authelia # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: Secure
    gethomepage.dev/description: "authelia"
    gethomepage.dev/widget.type: "authelia"
    gethomepage.dev/widget.url: "https://secure.trusted.nirmalhk7.com"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=authelia"
    gethomepage.dev/widget.key: L2cP2qFi88g2a6vMFrHBPiaGxJOrGUfHbFldFtRVXjxrDJyW3slG5gca1Sss
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`auth.trusted.nirmalhk7.com`)
      kind: Rule
      services:
        - name: authelia
          port: 80